### ISSUE TITLE
No data coming through

### ISSUE THREAD

**Issue by olgv** [lipemon1/airtableunity#1]
Hi there, 
First I want to say a big thank you for putting this together. 

I am reaching out with a small but essential problem... as I am not getting anything coming through from Airtable.

I was using the Prefab you have as an example (updating my App & Api keys) and all I get is: `Airtable Unity - Environment prepared successfully`

I did a test using just `AirtableRequestTest.cs` and I get the same Log message as above.
Looking in the class I see that there is a Debug.Log which should return a count... but this response by what ever reasons is not triggered.

I am using Unity 2019.4 (LTS)
Any advice is welcome

Thank you,

PS: happy to contribute in updating the documentation once getting this to work.

**Comment by lipemon1** [comment]
Sorry for the delay in the answer. 

The message `Airtable Unity - Environment prepared successfully` means that you are all set to request data. For the test I recommend use the ListRecordsExample.cs, you can find this script at `Assets\AirtableUnity\Scripts\Examples`.

After playing your project with this on any gameobject you can force a test clicking on 3 dots above the script at the editor and on `Get Table Records.` There is a ContextMenu attribute to enable this call.

I hope you can made this work after this. Let me know if not.

Best regards

**Comment by olgv** [comment]
That's great, thank you very much for getting back.
I also found the **TestCall**  ContextMenu on `AirtableRequestTest`, this is also helpful. 

Just one last question. When using the `GetRecordExample` I can point it to a Record ID, but how do you further point it to get a specific variable from that Record ID, based on the Field Name?

All works fine otherwise, thank you once again.

**Comment by lipemon1** [comment]
I'm glad the requests worked @olgv . You pumped me to add some other functionalities that were on my roadmap for this plugin. Thank you a lot for that.

BaseField

To get fields from your table you need to do this step:

Create a new class that has your airtable columns, an important thing is to avoid collum with space characters, if you are sure how this class is going to be you can get a JSON sample of them using the documentation link to your table.

`https://airtable.com/<**YOUR APP KEY HERE**>/api/docs#curl/table:links%20importantes:list`

On the right side of the screen, you will have a JSON example just like this

![image](https://user-images.githubusercontent.com/8778990/86513025-45853000-bddd-11ea-8524-10c5a96a2698.png)

This is a list of your current records, let's focus on the first one

![image](https://user-images.githubusercontent.com/8778990/86513070-83825400-bddd-11ea-967c-fdca6a14bd23.png)

Now, let's focus on the `fields` object

![image](https://user-images.githubusercontent.com/8778990/86513081-9ac14180-bddd-11ea-8fdd-f54a572a7d68.png)

This is going to be our class. Because on the Airtable Unity Package we have a class `BaseField` who holds the id, fields, and createdTime. This `BaseField` class receives a T parameter who is going to be your new class. In this case, I just showed our new class would have two properties:

> public class MyClass
> {
>      public string Nome;
>      public string Link;
> }

If your table has a lot of fields. I recommend you to use [this website](https://app.quicktype.io/?l=csharp) to create your c# class. 

After having your class you can call the following method <**public void GetAirtableTableRecords<T>**> inside ListRecordsExample.

![image](https://user-images.githubusercontent.com/8778990/86513317-a7469980-bddf-11ea-8583-8d7555db31c9.png)

Maybe you will need to change it to **public**

You should call this using BaseRecord<YOUR CLASS>. The call should be something like this:

![image](https://user-images.githubusercontent.com/8778990/86513286-559e0f00-bddf-11ea-9d7e-9da61e0a192a.png)

I hope you can make it work with these instructions. Ping me on any doubt

**Comment by lipemon1** [comment]
@olgv I hope you could make this work, I'm gonna close this issue. Just let me know if you have any other problem.

Best regards.

**Comment by olgv** [comment]
Thank you @lipemon1 ,we got it running in the end.
Struggling with getting it running in the build, but runs just fine in the editor.

**Comment by lipemon1** [comment]
Good to know that you get it running. If there is anything I can help you to run on the build, please let me know. I already had serious problems for loading local files on android mobile devices

**Comment by olgv** [comment]
Great, thank you. It is a straight macOS build, troubleshooting at the moment at a slow pace.

**Comment by olgv** [comment]
Yes, seems to be a problem here... running a Development Build (Unity 2019.4.7f1) on macOS (10.15.6) and getting: 
> [Message: Operation is not supported on this platform.] - [Request https://api.airtable.com/v0/.....]

 The error points to `Proxy.cs` line 136, `WebRequestExtension.cs` line 40 and last `Coroutines.cs` line 17
Same error seems to happen in a Windows build.

Thoughts appreciated.
Thank you

**Comment by lipemon1** [comment]
I will take a look on this script. I don't imagine what I'm using that is not supported. As soon as I check, I will let you know here
